name: GroceryApp CI/CD
on: 
  push:
    branches: [main]
  # pull_request:
  #   branches: [main]
jobs:
  build-and-upload:
    runs-on: macos-14
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with: 
        xcode-version: '16.3'
    - name: Set up Ruby environment
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.4.4'
    - name: Install Fastlane
      run: gem install fastlane
    - name: Run Fastlane beta lane
      env: 
        
